TITLE = "//span[@class='title']"
USER_FIRST_NAME = "Kristina"
USER_LAST_NAME = "Vlasenko"
PAYMENT_INFO = "//div[normalize-space()='Payment Information']"
INFO_TITLE = "Checkout: Your Information"
OVERVIEW_TITLE = "Checkout: Overview"
COMPLETE_TITLE = "Checkout: Complete!"
SUMMARY_FIRST_VALUE = "//div[@class='summary_value_label'][1]"
SUMMARY_LAST_VALUE = "//div[@class='summary_value_label'][2]"
SUMMARY_SUBTOTAL = "//div[@class='summary_subtotal_label']"
SUMMARY_TOTAL = "//div[@class='summary_info_label summary_total_label']"
SHIPPING_INFO = "//div[normalize-space()='Shipping Information']"
PRICE_TOTAL = "//div[normalize-space()='Price Total']"
FIRST_NAME = "id=first-name"
LAST_NAME = "id=last-name"
POSTAL_CODE_ID = "id=postal-code"
POSTAL_CODE_VALUE = "21001"
CONTINUE_BTN = "id=continue"
CANSEL_BTN = "id=cancel"
FINISH_BTN = "id=finish"
COMPLETE_TEXT = "Thank you for your order!"
BACK_HOME_BTN = "id=back-to-products"
CHECKOUT_BTN = "id=checkout"
ERROR_MSG = "//h3[@data-test='error']"
ERROR_EMPTY_FIELDS = "Error: First Name is required"
ERROR_EMPTY_LAST_NAME = "Error: Last Name is required"
ERROR_EMPTY_ZIP_CODE = "Error: Postal Code is required"



